### ISSUE TITLE
Markdown Support?

### ISSUE THREAD

**Issue by huphtur** [shwetank/quickhyperlink#2]
Would it be possible to detect if the user is editing a Markdown file and have it produce Markdown link syntax? 

``` md
This is [an example](http://example.com/) inline link.
```

**Comment by shwetank** [comment]
Yeah, I was thinking about this for a while, but later on forgot about implementing it. 

Thanks for reminding me, I've pushed an update. Instead of detecting whether the file is markdown or not, I have enabled it as another key binding (ctrl+alt+m). This is because since markdown supports html too, so in a markdown file a user might want to insert a link in the traditional markdown way, or even want to insert a link in the html way. 

Having support for both makes it possible for the user to add a link both ways. 

Hope that works.

**Comment by huphtur** [comment]
Nice, updated and worked like a charm! Thank you sir.

**Comment by shwetank** [comment]
Awesome
